In [1]:
string_1 = 'Hello World!'

In [2]:
print(string_1)

In [3]:
import numpy as np

In [4]:
#int32, float32
volume = 50
price = 100.54

In [5]:
print(type(volume))
print(type(price))

<class 'int'>
<class 'float'>


In [6]:
volume = np.int32(volume)
price = np.float32(price)

In [7]:
print(np.dtype(volume))
print(np.dtype(price))

int32
float32


In [8]:
array = np.array([1,2,3])
array

array([1, 2, 3])

In [9]:
array.dtype

dtype('int32')

In [10]:
array = np.array([1,2,3], dtype=np.float32)
array

array([1., 2., 3.], dtype=float32)

In [11]:
prices =[54.32,56,58.82,84.21]
prices = np.array(prices, dtype=np.float32)
prices.dtype

dtype('float32')

In [12]:
print(np.ones(5))
print(np.zeros(10))

[1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [13]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [14]:
print(np.arange(1,11))

[ 1  2  3  4  5  6  7  8  9 10]


In [15]:
print(np.arange(2,11,2))

[ 2  4  6  8 10]


In [16]:
print(np.linspace(1,9,5))

[1. 3. 5. 7. 9.]


In [17]:
prices

array([54.32, 56.  , 58.82, 84.21], dtype=float32)

In [18]:
prices[0]


54.32

In [19]:
prices[0:3]

array([54.32, 56.  , 58.82], dtype=float32)

In [20]:
prices.item(1)

56.0

In [21]:
print(prices.shape)
print(prices.size)

(4,)
4


In [22]:
print(prices.dtype)

float32


In [23]:
prices[1]=57.01
prices

array([54.32, 57.01, 58.82, 84.21], dtype=float32)

In [24]:
print(prices.tolist())
print(prices)

[54.31999969482422, 57.0099983215332, 58.81999969482422, 84.20999908447266]
[54.32 57.01 58.82 84.21]


In [25]:
print(type(prices.tolist()))
print(type(prices))

<class 'list'>
<class 'numpy.ndarray'>


In [26]:
prices.sort()

In [27]:
prices

array([54.32, 57.01, 58.82, 84.21], dtype=float32)

In [28]:
new_prices = np.array([100,100,100,100])
final_prices = new_prices + prices

In [29]:
final_prices

array([154.31999969, 157.00999832, 158.81999969, 184.20999908])

In [30]:
matrix = [[1,2],[3,4]]
matrix

[[1, 2], [3, 4]]

In [31]:
numpy_matrix = np.array(matrix)

In [32]:
numpy_matrix

array([[1, 2],
       [3, 4]])

In [33]:
one_to_ten = np.arange(1,11)
one_to_ten

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
matrix = one_to_ten.reshape((2,5))
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [39]:
grid = np.indices((2,3))
grid

array([[[0, 0, 0],
        [1, 1, 1]],

       [[0, 1, 2],
        [0, 1, 2]]])

In [40]:
prices = np.array([[1,2,3],[4,5,6],[7,8,9]])
prices

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
prices[1]

array([4, 5, 6])

In [42]:
prices[1][2]

6

In [43]:
print(prices.size)

9


In [44]:
print(prices.shape)
print(prices.dtype)

(3, 3)
int32


In [45]:
print(prices.min())
print(prices.max())

1
9


In [46]:
print(prices.min(axis=0))
print(prices.max(axis=1))

[1 2 3]
[3 6 9]


In [47]:
print(prices.min(axis=1))

[1 4 7]


In [48]:
prices[1].min()

4

In [50]:
print(prices.argmin(axis=0))
print(prices.argmax(axis=1))

[0 0 0]
[2 2 2]


In [51]:
prices

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
prices[0] = np.array([2,4,3])

In [53]:
prices

array([[2, 4, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
prices[0][1] = 5

In [55]:
prices

array([[2, 5, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
prices[0] = np.array([1,2,3])
prices

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
prices[2] = np.array()
prices

TypeError: array() missing required argument 'object' (pos 1)

In [58]:
prices[2] = ()
prices

ValueError: cannot copy sequence with size 0 to array axis with dimension 3

In [59]:
print(prices.reshape((1,9)))


[[1 2 3 4 5 6 7 8 9]]


In [60]:
prices = np.array([[1,2,3],[4,5,6]])
prices

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
reshaped_prices = prices.reshape((3,2))
print(reshaped_prices)
print(prices)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


In [62]:
prices.dot(reshaped_prices)

array([[22, 28],
       [49, 64]])

In [63]:
print(prices.transpose())

[[1 4]
 [2 5]
 [3 6]]


In [64]:
prices = np.array([[1,2,3],[4,5,6],[7,8,9]])
prices

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
print(prices.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]
